opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - all

disabled_rules: # rule identifiers turned on by default to exclude from running
  - no_extension_access_modifier
  - explicit_acl
  - explicit_type_interface
  - explicit_top_level_acl
  - required_deinit
  - explicit_enum_raw_value
  - sorted_enum_cases
  - no_grouping_extension
  - unused_capture_list
  - inert_defer
  - contrasted_opening_brace

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self

# Case-sensitive paths to include during linting. Directory paths supplied on the
# command line will be ignored.
included: 
  - Sources
  - Tests

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`

# If true, SwiftLint will not fail if no lintable files are found.
allow_zero_lintable_files: false

# If true, SwiftLint will treat all warnings as errors.
strict: false

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4
  excluded:
    - Log

identifier_name:
  min_length: 3
  excluded:
    - URL
    - url
    - id

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)

file_header:
  required_pattern: "© Copyright \\d{4}(-\\d{4})?, David W. Berry. All Rights Reserved."
